# Поддержка iOS 15
platform :ios, '15.0'

use_frameworks!
use_modular_headers!

target 'Runner' do
  flutter_application_path = '../'
  # подключаем podhelper.rb, если он есть
  load File.join(flutter_application_path, 'ios', 'Flutter', 'podhelper.rb') if File.exist?(File.join(flutter_application_path, 'ios', 'Flutter', 'podhelper.rb'))
end
